name: Deploy specification

on: [push, pull_request, workflow_dispatch]

jobs:
  deploy-spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: '15'
      - run: npm ci
      - run: npm run build
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Deploy assembled spec
        run: |
          git checkout -b assembled-spec
          git add -f openrpc.json
          git add -f refs-openrpc.json
          git commit -m "assemble openrpc.json"
          git push -fu origin assembled-spec
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: '15'
      - run: npm ci
      - run: npm run build
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          working-dir: build/docs/gatsby
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
